#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'servicios_types'

module Servicios
  class Client
    include ::Thrift::Client

    def obtenerCanciones(criterio)
      send_obtenerCanciones(criterio)
      return recv_obtenerCanciones()
    end

    def send_obtenerCanciones(criterio)
      send_message('obtenerCanciones', ObtenerCanciones_args, :criterio => criterio)
    end

    def recv_obtenerCanciones()
      result = receive_message(ObtenerCanciones_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'obtenerCanciones failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_obtenerCanciones(seqid, iprot, oprot)
      args = read_args(iprot, ObtenerCanciones_args)
      result = ObtenerCanciones_result.new()
      result.success = @handler.obtenerCanciones(args.criterio)
      write_result(result, oprot, 'obtenerCanciones', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class ObtenerCanciones_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    CRITERIO = 1

    FIELDS = {
      CRITERIO => {:type => ::Thrift::Types::STRING, :name => 'criterio'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class ObtenerCanciones_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Cancion}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

