#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class CancionSL
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDCANCION = 1
  TITULO = 2
  RUTA = 3
  ALBUM = 4
  ARTISTA = 5
  GENERO = 6
  CORREOARTISTA = 7
  IDALBUM = 8
  IDGENERO = 9

  FIELDS = {
    IDCANCION => {:type => ::Thrift::Types::I32, :name => 'idCancion'},
    TITULO => {:type => ::Thrift::Types::STRING, :name => 'titulo'},
    RUTA => {:type => ::Thrift::Types::STRING, :name => 'ruta'},
    ALBUM => {:type => ::Thrift::Types::STRING, :name => 'album'},
    ARTISTA => {:type => ::Thrift::Types::STRING, :name => 'artista'},
    GENERO => {:type => ::Thrift::Types::STRING, :name => 'genero'},
    CORREOARTISTA => {:type => ::Thrift::Types::STRING, :name => 'correoArtista'},
    IDALBUM => {:type => ::Thrift::Types::I32, :name => 'idAlbum'},
    IDGENERO => {:type => ::Thrift::Types::I32, :name => 'idGenero'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Consumidor
  include ::Thrift::Struct, ::Thrift::Struct_Union
  CORREO = 1
  NOMBRE = 2
  CLAVE = 3

  FIELDS = {
    CORREO => {:type => ::Thrift::Types::STRING, :name => 'correo'},
    NOMBRE => {:type => ::Thrift::Types::STRING, :name => 'nombre'},
    CLAVE => {:type => ::Thrift::Types::STRING, :name => 'clave'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Artista
  include ::Thrift::Struct, ::Thrift::Struct_Union
  CORREO = 1
  NOMBRE = 2
  CLAVE = 3

  FIELDS = {
    CORREO => {:type => ::Thrift::Types::STRING, :name => 'correo'},
    NOMBRE => {:type => ::Thrift::Types::STRING, :name => 'nombre'},
    CLAVE => {:type => ::Thrift::Types::STRING, :name => 'clave'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

