#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class CancionSL
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDCANCION = 1
  TITULO = 2
  RUTA = 3
  ALBUM = 4
  ARTISTA = 5
  GENERO = 6
  CORREOARTISTA = 7
  IDALBUM = 8
  IDGENERO = 9
  IMAGENALBUM = 10
  PUNTUACION = 11
  ANIOLANZAMIENTO = 12
  COMPANIADISCOGRAFICA = 13
  FECHA = 14
  DESCARGADA = 15

  FIELDS = {
    IDCANCION => {:type => ::Thrift::Types::I32, :name => 'idCancion'},
    TITULO => {:type => ::Thrift::Types::STRING, :name => 'titulo'},
    RUTA => {:type => ::Thrift::Types::STRING, :name => 'ruta'},
    ALBUM => {:type => ::Thrift::Types::STRING, :name => 'album'},
    ARTISTA => {:type => ::Thrift::Types::STRING, :name => 'artista'},
    GENERO => {:type => ::Thrift::Types::STRING, :name => 'genero'},
    CORREOARTISTA => {:type => ::Thrift::Types::STRING, :name => 'correoArtista'},
    IDALBUM => {:type => ::Thrift::Types::I32, :name => 'idAlbum'},
    IDGENERO => {:type => ::Thrift::Types::I32, :name => 'idGenero'},
    IMAGENALBUM => {:type => ::Thrift::Types::STRING, :name => 'imagenAlbum', :binary => true},
    PUNTUACION => {:type => ::Thrift::Types::I32, :name => 'puntuacion'},
    ANIOLANZAMIENTO => {:type => ::Thrift::Types::STRING, :name => 'anioLanzamiento'},
    COMPANIADISCOGRAFICA => {:type => ::Thrift::Types::STRING, :name => 'companiaDiscografica'},
    FECHA => {:type => ::Thrift::Types::STRING, :name => 'fecha'},
    DESCARGADA => {:type => ::Thrift::Types::STRING, :name => 'descargada'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Usuario
  include ::Thrift::Struct, ::Thrift::Struct_Union
  CORREO = 1
  NOMBRE = 2
  CLAVE = 3
  TIPO = 4
  FOTO = 5

  FIELDS = {
    CORREO => {:type => ::Thrift::Types::STRING, :name => 'correo'},
    NOMBRE => {:type => ::Thrift::Types::STRING, :name => 'nombre'},
    CLAVE => {:type => ::Thrift::Types::STRING, :name => 'clave'},
    TIPO => {:type => ::Thrift::Types::STRING, :name => 'tipo'},
    FOTO => {:type => ::Thrift::Types::STRING, :name => 'foto', :binary => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Playlist
  include ::Thrift::Struct, ::Thrift::Struct_Union
  NOMBRE = 1
  DESCRIPCION = 2
  IMAGEN = 3
  CORREO = 4
  IDPLAYLIST = 5

  FIELDS = {
    NOMBRE => {:type => ::Thrift::Types::STRING, :name => 'nombre'},
    DESCRIPCION => {:type => ::Thrift::Types::STRING, :name => 'descripcion'},
    IMAGEN => {:type => ::Thrift::Types::STRING, :name => 'imagen', :binary => true},
    CORREO => {:type => ::Thrift::Types::STRING, :name => 'correo'},
    IDPLAYLIST => {:type => ::Thrift::Types::I32, :name => 'idPlaylist'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Historial
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDCANCION = 1
  CORREO = 2
  FECHA = 3

  FIELDS = {
    IDCANCION => {:type => ::Thrift::Types::I32, :name => 'idCancion'},
    CORREO => {:type => ::Thrift::Types::STRING, :name => 'correo'},
    FECHA => {:type => ::Thrift::Types::STRING, :name => 'fecha'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Biblioteca
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDCANCION = 1
  CORREO = 2
  PUNTUACION = 3
  DESCARGADA = 4

  FIELDS = {
    IDCANCION => {:type => ::Thrift::Types::I32, :name => 'idCancion'},
    CORREO => {:type => ::Thrift::Types::STRING, :name => 'correo'},
    PUNTUACION => {:type => ::Thrift::Types::I32, :name => 'puntuacion'},
    DESCARGADA => {:type => ::Thrift::Types::STRING, :name => 'descargada'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Contenido
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDCANCION = 1
  IDPLAYLIST = 2

  FIELDS = {
    IDCANCION => {:type => ::Thrift::Types::I32, :name => 'idCancion'},
    IDPLAYLIST => {:type => ::Thrift::Types::I32, :name => 'idPlaylist'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class AlbumSL
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDALBUM = 1
  TITULO = 2
  IMAGENALBUM = 3
  NOMBREARTISTA = 4
  CORREO = 5
  ANIOLANZAMIENTO = 6
  COMPANIADISCOGRAFICA = 7

  FIELDS = {
    IDALBUM => {:type => ::Thrift::Types::I32, :name => 'idAlbum'},
    TITULO => {:type => ::Thrift::Types::STRING, :name => 'titulo'},
    IMAGENALBUM => {:type => ::Thrift::Types::STRING, :name => 'imagenAlbum', :binary => true},
    NOMBREARTISTA => {:type => ::Thrift::Types::STRING, :name => 'nombreArtista'},
    CORREO => {:type => ::Thrift::Types::STRING, :name => 'correo'},
    ANIOLANZAMIENTO => {:type => ::Thrift::Types::STRING, :name => 'anioLanzamiento'},
    COMPANIADISCOGRAFICA => {:type => ::Thrift::Types::STRING, :name => 'companiaDiscografica'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Genero
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDGENERO = 1
  NOMBREGENERO = 2

  FIELDS = {
    IDGENERO => {:type => ::Thrift::Types::I32, :name => 'idGenero'},
    NOMBREGENERO => {:type => ::Thrift::Types::STRING, :name => 'nombreGenero'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Album
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDALBUM = 1
  TITULO = 2
  IMAGENALBUM = 3
  CORREO = 4
  ANIOLANZAMIENTO = 5
  COMPANIADISCOGRAFICA = 6

  FIELDS = {
    IDALBUM => {:type => ::Thrift::Types::I32, :name => 'idAlbum'},
    TITULO => {:type => ::Thrift::Types::STRING, :name => 'titulo'},
    IMAGENALBUM => {:type => ::Thrift::Types::STRING, :name => 'imagenAlbum', :binary => true},
    CORREO => {:type => ::Thrift::Types::STRING, :name => 'correo'},
    ANIOLANZAMIENTO => {:type => ::Thrift::Types::STRING, :name => 'anioLanzamiento'},
    COMPANIADISCOGRAFICA => {:type => ::Thrift::Types::STRING, :name => 'companiaDiscografica'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Cancion
  include ::Thrift::Struct, ::Thrift::Struct_Union
  IDCANCION = 1
  TITULO = 2
  RUTA = 3
  IDALBUM = 4
  IDGENERO = 5

  FIELDS = {
    IDCANCION => {:type => ::Thrift::Types::I32, :name => 'idCancion'},
    TITULO => {:type => ::Thrift::Types::STRING, :name => 'titulo'},
    RUTA => {:type => ::Thrift::Types::STRING, :name => 'ruta'},
    IDALBUM => {:type => ::Thrift::Types::I32, :name => 'idAlbum'},
    IDGENERO => {:type => ::Thrift::Types::I32, :name => 'idGenero'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

